### ISSUE TITLE
How to distribute input data among computing nodes?

### ISSUE THREAD

**Issue by dreamedcheng** [epfl-labos/chaos#4]
Hi, I am trying to use chaos, but I found no tools provided by chaos to distribute the input data
to different computing nodes. Should I write it by myself or do you have any recommendations of open
source tools. By the way, if I do not split the input data, and place it at every nodes, will it influence the correctness of the final result? If not, will it degrade the performance?
  Thanks in advance.

**Comment by bindsch** [comment]
This can be done in any way you want as long as you are careful not to cut in the middle of an edge. For best performance, each node should have the same amount of input data to process, but correctness will not be impacted even if a single node has all the input data.

I recommend using `split`. Also, if you are using our RMAT generator, you need not worry about this since the tool can already generate a subset of the input graph.

**Comment by dreamedcheng** [comment]
Got it.
Thanks a lot.
